#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Regenerates bpf/vmlinux/<arch>/vmlinux.h from Debian's signed 6.18 LTS
# kernel packages (CONFIG_DEBUG_INFO_BTF=y), for x86_64 and arm64.
# Runs in Docker; provenance is recorded in bpf/include/README.md.
#
#   bpf/scripts/gen-vmlinux.sh            # regenerate both arches
#   KERNEL_ABI=6.18.9+deb13 KERNEL_PKG_VERSION=6.18.9-1~bpo13+1 bpf/scripts/gen-vmlinux.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
KERNEL_ABI="${KERNEL_ABI:-6.18.9+deb13}"
KERNEL_PKG_VERSION="${KERNEL_PKG_VERSION:-6.18.9-1~bpo13+1}"
FLAVOUR="${FLAVOUR:-cloud}"
# scripts/extract-vmlinux from the v6.18 tag, pinned by hash.
EXTRACT_URL="https://raw.githubusercontent.com/torvalds/linux/v6.18/scripts/extract-vmlinux"
EXTRACT_SHA256="aacb6bb09af227a6cf508f5283458f001722a39abd9c4cfb026bc97c31624910"

if [[ "${VESTA_IN_CONTAINER:-}" != "1" ]]; then
	exec docker run --rm -e VESTA_IN_CONTAINER=1 -e DEBIAN_FRONTEND=noninteractive \
		-e KERNEL_ABI -e KERNEL_PKG_VERSION -e FLAVOUR \
		-v "${repo_root}:/src" -w /src debian:trixie-slim bpf/scripts/gen-vmlinux.sh
fi

echo "deb http://deb.debian.org/debian trixie-backports main" >/etc/apt/sources.list.d/backports.list
dpkg --add-architecture arm64
apt-get update -qq
apt-get install -y -qq --no-install-recommends bpftool python3 curl ca-certificates file binutils \
	xz-utils zstd gzip bzip2 lz4 >/dev/null

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT
curl -fsSL "${EXTRACT_URL}" -o "${work}/extract-vmlinux"
echo "${EXTRACT_SHA256}  ${work}/extract-vmlinux" | sha256sum -c - >/dev/null
chmod +x "${work}/extract-vmlinux"

for pair in amd64:x86_64 arm64:arm64; do
	deb_arch="${pair%%:*}"
	out_arch="${pair##*:}"
	pkg="linux-image-${KERNEL_ABI}-${FLAVOUR}-${deb_arch}-unsigned"
	dir="${work}/${deb_arch}"
	mkdir -p "${dir}"
	# apt verifies the package against the signed Release file.
	(cd "${dir}" && apt-get download -qq "${pkg}:${deb_arch}=${KERNEL_PKG_VERSION}")
	deb="$(ls "${dir}"/*.deb)"
	dpkg-deb -x "${deb}" "${dir}/root"
	"${work}/extract-vmlinux" "${dir}/root/boot/vmlinuz-${KERNEL_ABI}-${FLAVOUR}-${deb_arch}" >"${dir}/vmlinux" 2>/dev/null
	python3 bpf/scripts/btf-carve.py "${dir}/vmlinux" "${dir}/vmlinux.btf"
	mkdir -p "bpf/vmlinux/${out_arch}"
	{
		echo "/* Generated by bpf/scripts/gen-vmlinux.sh from Debian ${pkg} ${KERNEL_PKG_VERSION}. Do not edit. */"
		bpftool btf dump file "${dir}/vmlinux.btf" format c
	} >"bpf/vmlinux/${out_arch}/vmlinux.h"
	echo "${out_arch}: $(basename "${deb}") sha256=$(sha256sum "${deb}" | cut -d' ' -f1) bpftool=$(bpftool version | head -1)"
done
