#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Helm chart checks and the plain-manifest rendering in deploy/manifests/.
#   hack/helm.sh lint         helm lint --strict with the default and alternate values
#   hack/helm.sh render       regenerate deploy/manifests/vesta.yaml
#   hack/helm.sh check        fail if deploy/manifests/vesta.yaml is stale
#   hack/helm.sh kubeconform  validate rendered manifests against Kubernetes schemas
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
chart="deploy/helm/vesta"
manifest="deploy/manifests/vesta.yaml"
namespace="vesta-system"
k8s_version="1.34.1"
helm_image="alpine/helm:3.19.0@sha256:aef9b56f64e866207d9591d0abd8f6d767b36aadd12edf68f8a719716d9d29c9"
kubeconform_image="ghcr.io/yannh/kubeconform:v0.7.0@sha256:85dbef6b4b312b99133decc9c6fc9495e9fc5f92293d4ff3b7e1b30f5611823c"

helm() {
	docker run --rm -v "${repo_root}:/src:ro" -w /src -e HELM_CACHE_HOME=/tmp -e HELM_CONFIG_HOME=/tmp \
		"${helm_image}" "$@"
}

render() {
	printf '# SPDX-License-Identifier: Apache-2.0\n# Generated by hack/helm.sh render from %s with default values. Do not edit.\n' "${chart}"
	helm template vesta "${chart}" --namespace "${namespace}" --kube-version "${k8s_version}" --include-crds
}

case "${1:-}" in
lint)
	helm lint --strict "${chart}"
	helm lint --strict "${chart}" --set installer.containerdFlavor=k3s \
		--set metrics.service.enabled=true --set metrics.podMonitor.enabled=true \
		--set agent.image.digest=sha256:0000000000000000000000000000000000000000000000000000000000000000 \
		--set installer.restartContainerd=false --set agent.seccomp.installProfile=false \
		--set-json 'staticPolicies=[{"apiVersion":"vesta.dev/v1alpha1","kind":"VestaPolicy","metadata":{"name":"baseline"},"spec":{}}]'
	helm lint --strict "${chart}" --set uninstall.enabled=true --set nri.requirePluginAnnotation=true \
		--set metrics.exposeOnNodeIP=true
	helm lint --strict "${chart}" --set policies.source=kubernetes
	;;
render)
	render >"${repo_root}/${manifest}"
	echo "wrote ${manifest}"
	;;
check)
	if ! diff -u "${repo_root}/${manifest}" <(render); then
		echo "${manifest} is stale; run hack/helm.sh render" >&2
		exit 1
	fi
	echo "${manifest} is up to date"
	;;
kubeconform)
	# The PodMonitor CRD schema is not in the default catalog.
	{
		cat "${repo_root}/${manifest}"
		echo "---"
		helm template vesta "${chart}" --namespace "${namespace}" --kube-version "${k8s_version}" \
			--set installer.containerdFlavor=rke2 --set metrics.service.enabled=true --set metrics.podMonitor.enabled=true
		echo "---"
		helm template vesta "${chart}" --namespace "${namespace}" --kube-version "${k8s_version}" \
			--set uninstall.enabled=true --set nri.requirePluginAnnotation=true
		echo "---"
		helm template vesta "${chart}" --namespace "${namespace}" --kube-version "${k8s_version}" \
			--set policies.source=kubernetes
	} | docker run --rm -i "${kubeconform_image}" -strict -summary \
		-kubernetes-version "${k8s_version}" -skip PodMonitor,CustomResourceDefinition -
	# kubeconform has no schema for CustomResourceDefinition itself; the CRD is
	# checked against a real API server by hack/crd-check.sh.
	docker run --rm -v "${repo_root}/deploy/manifests:/m:ro" "${kubeconform_image}" -strict -summary \
		-kubernetes-version "${k8s_version}" -skip CustomResourceDefinition -ignore-filename-pattern 'kustomization.yaml' /m
	;;
*)
	echo "usage: $0 lint|render|check|kubeconform" >&2
	exit 2
	;;
esac
