# SPDX-License-Identifier: Apache-2.0
# Start kata-agent after vesta-guestd has attached its programs (it signals
# READY=1). Wants= rather than Requires=: a failed guestd does not stop the
# agent (fail-open at boot); the host reports the sandbox as degraded.
[Unit]
Wants=vesta-guestd.service
After=vesta-guestd.service
